### ISSUE TITLE
Add color to the output

### ISSUE THREAD

**Issue by sudarkoff** [SurveyMonkey/defrost#7]
Yeah, I know, I know... But `click` makes it so easy! :)

And it definitely should be possible to turn the color off with `--no-color` or whatnot.

**Comment by aconrad** [comment]
I feel this would be a task for @msabramo :P

**Comment by aconrad** [comment]
How would you see the output colored?

**Comment by sudarkoff** [comment]
Oh, I definitely think there are more important features to implement before color. :)
